# Generated by Django 5.2.11 on 2026-02-14 00:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Original ID from source', max_length=255, unique=True)),
                ('source', models.CharField(choices=[('HN', 'Hacker News'), ('REDDIT_LOCALLLAMA', 'r/LocalLLaMA'), ('REDDIT_MACHINELEARNING', 'r/MachineLearning'), ('REDDIT_PROGRAMMING', 'r/programming'), ('GITHUB', 'GitHub'), ('TWITTER', 'Twitter/X'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('engagement_score', models.IntegerField(default=0, help_text='Score/points from the source platform')),
                ('comment_count', models.IntegerField(default=0)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Sentiment score from VADER analysis (-1.0 to 1.0)')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, help_text='Full text content if available', null=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('LLM', 'Large Language Model'), ('FRAMEWORK', 'Framework'), ('LIBRARY', 'Library'), ('TOOL', 'Tool'), ('PHILOSOPHY', 'Philosophy'), ('PLATFORM', 'Platform'), ('LANGUAGE', 'Programming Language'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this topic is actively being tracked')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'category'], name='api_topic_name_69d950_idx'), models.Index(fields=['is_active', 'created_at'], name='api_topic_is_acti_1bf2a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1.0, help_text='How relevant is this topic to the post (0.0 to 1.0)')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary topic of the post?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.post')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.topic')),
            ],
            options={
                'verbose_name': 'Topic Mention',
                'verbose_name_plural': 'Topic Mentions',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='posts', through='api.TopicMention', to='api.topic'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momentum_threshold', models.FloatField(default=2.0, help_text='Alert when momentum score exceeds this value')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='api.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
            },
        ),
        migrations.CreateModel(
            name='TopicDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_mentions', models.IntegerField(default=0, help_text='Count of posts mentioning this topic on this day')),
                ('total_engagement', models.IntegerField(default=0, help_text='Sum of engagement scores for this day')),
                ('avg_sentiment', models.FloatField(default=0.0, help_text='Average sentiment score for this day')),
                ('momentum_score', models.FloatField(default=0.0, help_text='Calculated velocity vs. previous day (change in mentions)')),
                ('engagement_momentum', models.FloatField(default=0.0, help_text='Change in total engagement vs. previous day')),
                ('source_breakdown', models.JSONField(blank=True, default=dict, help_text="JSON object with mention counts per source, e.g., {'HN': 5, 'REDDIT_LOCALLLAMA': 3}")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='api.topic')),
            ],
            options={
                'verbose_name': 'Topic Daily Metric',
                'verbose_name_plural': 'Topic Daily Metrics',
                'ordering': ['-date', 'topic'],
                'indexes': [models.Index(fields=['topic', '-date'], name='api_topicda_topic_i_11eb48_idx'), models.Index(fields=['-date', '-momentum_score'], name='api_topicda_date_d2abf9_idx'), models.Index(fields=['-momentum_score'], name='api_topicda_momentu_c4c893_idx'), models.Index(fields=['-engagement_momentum'], name='api_topicda_engagem_ed0b7f_idx')],
                'unique_together': {('topic', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='topicmention',
            index=models.Index(fields=['topic', 'post'], name='api_topicme_topic_i_665692_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmention',
            index=models.Index(fields=['is_primary'], name='api_topicme_is_prim_3ea7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmention',
            index=models.Index(fields=['relevance_score'], name='api_topicme_relevan_d8ffd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicmention',
            unique_together={('topic', 'post')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['source', 'published_at'], name='api_post_source_9ea2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['engagement_score', 'published_at'], name='api_post_engagem_ecb272_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['sentiment_score'], name='api_post_sentime_60ed4b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='api_post_publish_7d62c5_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'enabled'], name='api_watchli_user_id_49ec43_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['topic', 'enabled'], name='api_watchli_topic_i_e048a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'topic')},
        ),
    ]
