# Generated by Django 5.2.11 on 2026-02-14 01:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, help_text='The canonical/official name', max_length=255, unique=True)),
                ('entity_type', models.CharField(choices=[('LLM_FAMILY', 'LLM Family'), ('FRAMEWORK', 'Framework'), ('LIBRARY', 'Library'), ('TOOL', 'Tool'), ('PLATFORM', 'Platform'), ('LANGUAGE', 'Programming Language'), ('CONCEPT', 'Concept'), ('COMPANY', 'Company'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, default=None, help_text='Vector embedding for semantic search (list of floats)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['canonical_name', 'entity_type'], name='api_entity_canonic_3aa271_idx'), models.Index(fields=['is_active', 'created_at'], name='api_entity_is_acti_de9ab3_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, help_text='Specific version/variation name', max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list, help_text="Alternative names/spellings (e.g., ['Opus 4.6', 'Sonnet 4.6'])")),
                ('embedding', models.JSONField(blank=True, default=None, help_text='Vector embedding for semantic search (list of floats)', null=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence that this node belongs to parent (0.0-1.0)')),
                ('resolution_method', models.CharField(choices=[('MANUAL', 'Manual'), ('VECTOR', 'Vector Clustering'), ('LLM', 'LLM Resolution'), ('HYBRID', 'Hybrid')], default='MANUAL', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(help_text='Parent canonical entity', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.entity')),
            ],
            options={
                'verbose_name': 'Entity Node',
                'verbose_name_plural': 'Entity Nodes',
            },
        ),
        migrations.CreateModel(
            name='TopicEntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0, help_text='Cosine similarity score (0.0-1.0)')),
                ('resolution_method', models.CharField(choices=[('EXACT', 'Exact Match'), ('VECTOR', 'Vector Similarity'), ('LLM', 'LLM Resolution')], default='EXACT', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='api.entity')),
                ('entity_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='api.entitynode')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='api.topic')),
            ],
            options={
                'verbose_name': 'Topic-Entity Link',
                'verbose_name_plural': 'Topic-Entity Links',
            },
        ),
        migrations.AddIndex(
            model_name='entitynode',
            index=models.Index(fields=['parent', 'label'], name='api_entityn_parent__0f3324_idx'),
        ),
        migrations.AddIndex(
            model_name='entitynode',
            index=models.Index(fields=['confidence_score'], name='api_entityn_confide_4015fe_idx'),
        ),
        migrations.AddIndex(
            model_name='entitynode',
            index=models.Index(fields=['resolution_method'], name='api_entityn_resolut_c348c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitynode',
            unique_together={('parent', 'label')},
        ),
        migrations.AddIndex(
            model_name='topicentitylink',
            index=models.Index(fields=['topic', 'entity'], name='api_topicen_topic_i_f6794e_idx'),
        ),
        migrations.AddIndex(
            model_name='topicentitylink',
            index=models.Index(fields=['topic', 'entity_node'], name='api_topicen_topic_i_75fd35_idx'),
        ),
        migrations.AddIndex(
            model_name='topicentitylink',
            index=models.Index(fields=['similarity_score'], name='api_topicen_similar_ada4a7_idx'),
        ),
    ]
