# Generated by Django 5.1.3 on 2026-03-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entity_entitynode_topicentitylink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdailymetric',
            name='growth_rate',
            field=models.FloatField(default=0.0, help_text='Percentage growth in mentions vs. previous day (0.0 = no change, 1.0 = 100% growth)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('HN', 'Hacker News'), ('REDDIT_LOCALLLAMA', 'r/LocalLLaMA'), ('REDDIT_MACHINELEARNING', 'r/MachineLearning'), ('REDDIT_PROGRAMMING', 'r/programming'), ('GITHUB', 'GitHub'), ('TWITTER', 'Twitter/X'), ('PRODUCT_HUNT', 'Product Hunt'), ('DEVTO', 'Dev.to'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
    ]
