# Generated by Django 5.1.3 on 2026-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_growth_rate_to_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('HN', 'Hacker News'), ('REDDIT_LOCALLLAMA', 'r/LocalLLaMA'), ('REDDIT_MACHINELEARNING', 'r/MachineLearning'), ('REDDIT_PROGRAMMING', 'r/programming'), ('GITHUB', 'GitHub'), ('GITHUB_TRENDING', 'GitHub Trending'), ('TWITTER', 'Twitter/X'), ('PRODUCT_HUNT', 'Product Hunt'), ('DEVTO', 'Dev.to'), ('INDIEHACKERS', 'Indie Hackers'), ('LOBSTERS', 'Lobste.rs'), ('TAAFT', "There's An API For That"), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
    ]
